title: PP_ART Portfolio Theme 
email: ppuente86@ymail.com
brand: PP_ART
description: Working my way to be a better 'Data Scientist' everyday.
show_downloads: true
copyright: "1986 Pepe's Company, Inc. All Rights Reserved."

# Build settings
markdown: kramdown

# Account ids
snapwidget: 
# Contacts
email: ppuente86@ymail.com 


# Tracking
googleAnalitycsID: 


theme: jekyll-theme-hacker

