# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: ppuente86@ymail.com
brand: PP_ART
headline: Working my way to be a better 'Data Scientist' everyday.
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: "1986 Pepe's Company, Inc. All Rights Reserved."

# Build settings
markdown: kramdown

# Account ids
snapwidget: 
# Contacts
email: ppuente86@ymail.com 


# Tracking
googleAnalitycsID: 


theme: jekyll-theme-hacker